name: Fetch GCP Project ID (DEV)

on:
  push: # Trigger on pushes to any branch

env:
  TARGET_ENV: 'main'
  MAIN_SECRETS: ${{ secrets.MAIN_SECRETS }}

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Debug environment variables
        run: printenv

      - name: Use the secret
        run: echo "The secret value is:" $MAIN_SECRETS
