name: Fetch GCP Project ID (DEV)

on:
  push: # Trigger on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Use the secret
        env:
          MAIN_SECRETS: ${{ secrets.MAIN_SECRETS }}
        run: echo "The secret value is: ${{ env.MAIN_SECRETS }}"
