name: Fetch GCP Project ID (DEV)

on:
  push: # Trigger on pushes to any branch

runs-on: ubuntu-latest  # Replace with your desired runner

env:
  MAIN_SECRETS: ${{ secrets.MAIN_SECRETS }}

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with your desired runner
    steps:
      - name: Use the secret
        run: echo "The secret value is:" $MAIN_SECRETS
